config/routes.rb
Japify::Application.routes.draw do
  resources :pages
  resources :auctions
  # resources :sellers
  
  match '/search/:query' => "pages#search", :as => :search
  match '/seller/:seller'  => "pages#seller", :as => :seller
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => "sessions#destroy", :as => :signout
  
  root :to => "pages#index"
end

app/views/pages/_page_list.html.erb
<%= paginate @pages %>

<p>
<table>
  <tr>
    <th>Name</th>
    <th>Query</th>
    <th>Category</th>
    <th>Link</th>
  </tr>
  <% for page in @pages %>
    <tr>
      <td><%= link_to page.name, page_path(page) %></td>
      <td><%= page.query %></td>
      <td><%= page.category %></td>
      <td><%= link_to "url", page.url %></td>      
      <td><%= link_to "Destroy", page, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
<p>
<%= paginate @pages %>

app/views/pages/index.html.erb
<% title "Pages" %>

<%= render :partial => 'page_list' %>

<p><%= link_to "New Page", new_page_path %></p>

app/views/pages/index.iphone.erb
<div class="toolbar">
  <h1 id="pageTitle">Pages</h1>
  <%= link_to 'back', '#', :id => 'backButton', :class => 'button' %>  
  <%= link_to 'Search', '#searchForm', :class => 'button' %>
</div>

<ul title='Pages' selected="true">
  <% for page in @pages %>
    <li>
      <%= link_to page.name, page_path(page) %>
    </li>
  <% end %>
</ul>

<% form_tag search_path, :id => 'searchForm', :class => 'dialog' do %>
  <fieldset>
    <h1>Search</h1>
    <%= link_to 'Cancel', '#', :class => 'button leftButton', :type => 'cancel' %>
    <%= link_to 'Search', '#', :class => 'button blueButton', :type => 'submit' %>  
    <label for="query">Search</label>
    <%= text_field_tag :query %>
  </fieldset>
<% end %>

app/views/pages/new.html.erb
<% title "New Page" %>

<%= form_for @page do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :query %><br />
    <%= f.text_field :query %>
  </p>
  <p><%= f.submit %></p>
<% end %>


<p><%= link_to "Back to List", pages_path %></p>

app/views/pages/search.html.erb
<% title "Search Result" %>

<%= render :partial => 'page_list' %>

app/views/pages/search.iphone.erb
<ul title='Search Result' selected="true">
  <% for page in @pages %>
    <li>
      <%= link_to page.name, page_path(page) %>
    </li>
  <% end %>
</ul>

app/views/pages/seller.html.erb
<% javascript 'jquery.translate.min' %>
<% javascript 'translate' %>


<% title @page.name %>

<%= render :partial => 'shared/auction_list' %>

app/views/pages/show.html.erb
<% javascript 'jquery.translate.min' %>
<% javascript 'translate' %>


<% title @page.name %>

<%= render :partial => 'shared/auction_list' %>

app/views/pages/show.iphone.erb
<ul selected="true">
<% @page.auctions['auctions'].each do |auction| %>
  <li>
    <%= link_to image_tag(auction.image_icon), auction_path(auction) %> 
    <%= auction.title %>
    <%= yen auction.current_price %>
  </li>
<% end %>
</ul>