config/routes.rb
Japify::Application.routes.draw do
  resources :pages
  resources :auctions
  # resources :sellers
  
  match '/search/:query' => "pages#search", :as => :search
  match '/seller/:seller'  => "pages#seller", :as => :seller
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => "sessions#destroy", :as => :signout
  
  root :to => "pages#index"
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'jquery-1.5.min.js' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if current_user %>
          Welcome, <%= current_user.name %>!
          <%= link_to "Sign Out", signout_path %>
        <% else %>
          <%= link_to "Sign in with Twitter", "/auth/twitter" %>
          <%= link_to "Sign in with Facebook", "/auth/facebook" %>
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <% begin %>
        <%= yield  %>
      <% rescue %>
        <%= yield.force_encoding("ASCII-8BIT") %>
      <% end %>
    </div>  
  </body>
</html>

app/views/layouts/application.iphone.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <meta id="viewport" name="viewport" content="width=device.width; initial-scale=1.0"></meta>
    <%= stylesheet_link_tag 'iui' %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'jquery-1.5.min.js' %>
    <%= javascript_include_tag 'iui' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= yield  %>
  </body>
</html>